
spring:
  datasource:
    url: jdbc:mysql://119.23.219.183:3306/naicha?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: zxd
    password: ZHAOxudong123.
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    suffix: .html
    prefix: classpath:/templates/
    mode: HTML5
    cache: false
  mvc:
    static-path-pattern: /*
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:com.example.quiz/*.xml
  type-aliases-package: com.example.quiz
server:
  port: 8060
  servlet:
    context-path: /
